all:
	make -C lib_geometry
	make -C lib_strings
	make -C lab02
	#make -C lab03
	make -C lab04
	make -C lab05
	make -C lab06

clean:
	make -C lib_geometry clean
	make -C lib_strings clean
	make -C lab02 clean
	#make -C lab03 clean
	make -C lab04 clean
	make -C lab05 clean
	make -C lab06 clean
