all: factorial factorial_longint str_search

factorial: factorial.cpp
	g++ -o factorial factorial.cpp

factorial_longint: factorial_longint.cpp
	g++ -o factorial_longint factorial_longint.cpp

str_search: str_search.cpp
	g++ -o str_search str_search.cpp

clean:
	rm -f factorial factorial_longint str_search *~
