libgeometry.a : Vertex.cpp Vertex.h VertexSimple.cpp VertexSimple.h SegList.cpp SegList.h Square.cpp Square.h Triangle.cpp Triangle.h TriangleV2.h TriangleV2.cpp SquareV2.h SquareV2.cpp SegListV2.cpp SegListV2.h SegListV3.cpp SegListV3.h SquareV3.h SquareV3.cpp TriangleV3.h TriangleV3.cpp SegListV4.cpp SegListV4.h SquareV4.h SquareV4.cpp TriangleV4.h TriangleV4.cpp 
	g++ -c Vertex.cpp VertexSimple.cpp SegList.cpp Square.cpp Triangle.cpp SquareV2.cpp TriangleV2.cpp SegListV2.cpp TriangleV3.cpp SquareV3.cpp SegListV3.cpp TriangleV4.cpp SquareV4.cpp SegListV4.cpp
	ar cr libgeometry.a Vertex.o VertexSimple.o SegList.o Square.o Triangle.o SquareV2.o TriangleV2.o SegListV2.o TriangleV3.o SquareV3.o SegListV3.o TriangleV4.o SquareV4.o SegListV4.o


clean:
	rm -f Vertex.o VertexSimple.o SegList.o Square.o Triangle.o SquareV2.o TriangleV2.o libgeometry.a *~ SegListV2.o SegListV3.o TriangleV3.o SquareV3.o TriangleV4.o SquareV4.o SegListV4.o

