all: function_sepdef function_hellocap

function_sepdef: function_sepdef.cpp
	g++ -o function_sepdef function_sepdef.cpp

function_hellocap: function_hellocap.cpp
	g++ -o function_hellocap function_hellocap.cpp

clean:
	rm -f function_hellocap function_main
	rm -f function_sepdef *~
